{% set name = "pypyodbc" %}
{% set version = "1.3.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # Use GH for LICENSE file and upstream tests
  url: https://github.com/pypyodbc/pypyodbc/archive/refs/tags/v1.3.6.tar.gz
  sha256: 14cdc66381c4204578f78512f0eb24515e0ab114f8de0cf398862a53407d99a2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    #- unixodbc  # [unix]
  run:
    - python

test:
  imports:
    - pypyodbc

about:
  home: https://github.com/pypyodbc/pypyodbc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pure Python Cross Platform ODBC interface module
  doc_url: https://github.com/pypyodbc/pypyodbc/wiki
  dev_url: https://github.com/pypyodbc/pypyodbc

extra:
  recipe-maintainers:
    - nwani
